### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by DevVigilante** [Sidmaz666/rongin#1]
Either remove nav bar in the preview or just improve it a little bit my using icons instead of text in that.
All things are perfect in my opinion excluding the nav bar in preview

**Comment by Sidmaz666** [comment]
> Either remove nav bar in the preview or just improve it a little bit my using icons instead of text in that. All things are perfect in my opinion excluding the nav bar in preview

You mean add icons instead of text such as `Home` , `About` and `Contact` ?

**Comment by DevVigilante** [comment]
> > Either remove nav bar in the preview or just improve it a little bit my using icons instead of text in that. All things are perfect in my opinion excluding the nav bar in preview
> 
> You mean add icons instead of text such as `Home` , `About` and `Contact` ?

Yes and also increase padding a bit more

**Comment by Sidmaz666** [comment]
> > > Either remove nav bar in the preview or just improve it a little bit my using icons instead of text in that. All things are perfect in my opinion excluding the nav bar in preview
> > 
> > 
> > You mean add icons instead of text such as `Home` , `About` and `Contact` ?
> 
> Yes and also increase padding a bit more

I have tried using icons instead of text, but it doesn't look good and more padding will result in bad mobile UI, therefore I think I will close the issue since these are not major factors that will effect the color generation and anyone could cope up with the preview section. Thank you for your suggestions.
